name: Terraform Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init -backend-config="organization=Eagle_Industries" -backend-config="workspace=${{ vars.REPO_NAME }}"
        env:
          TF_API_TOKEN: ${{ secrets.TF_TOKEN }}

      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan
        env:
          TF_API_TOKEN: ${{ secrets.TF_TOKEN }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply plan.tfplan
        env:
          TF_API_TOKEN: ${{ secrets.TF_TOKEN }}